Repository MoyeoProject/moyeo-FE, pull requests merged in 2023-02, with the labels that each got.

#160 [S-5] 검색페이지를 따로 분리하라
  src/App.tsx
  src/components/common/TopNavBar.tsx
  src/pages/HomePage.tsx
  src/pages/SearchPage.tsx
  src/styles/MeetingListStyle.ts
  src/styles/SearchFormStyle.ts
Labels: feature

#163 [S-5] 마이프로필 서브페이지 생성 및 수정
  src/pages/FollowPage.tsx
  src/pages/SettingPage.tsx
Labels: feature

#164 [S-5] 상세페이지 정보 탭 이미지 추가
  src/components/common/DetailMeetingInfo.tsx
  src/styles/DetailMeetingInfoStyle.ts
Labels: feature

#165 [S-5] 회원가입 이메일 인증구현 완성, 비밀번호 변경 페이지 구현
  src/pages/LoginPage.tsx
  src/pages/RePasswordPage.tsx
  src/pages/SignupPage.tsx
  src/services/api.ts
Labels: feature

#166 [S-5] 프로필페이지에서 사진편집 버튼 수정
  src/components/MiniModal.tsx
  src/components/ProfileModalForm.tsx
  src/styles/ModalStyle.ts
Labels: feature

#167 [S-5] 작성/수정페이지에 삭제, 이미지업로드 기능 구현
  src/hooks/useChangePostForm.ts
  src/pages/PostPage.tsx
  src/services/api.ts
  src/styles/FormStyle.ts
  src/styles/GlobalStyle.ts
Labels: feature

#171 [S-5] 상세페이지 이미지 수정버튼 기능을 추가하였습니다
  src/components/DetailImgEditModal.tsx
  src/components/common/DetailMeetingInfo.tsx
  src/services/api.ts
  src/styles/ModalStyle.ts
Labels: feature

#172 [S-5] 로그인 시, 토큰 만료 에러 임시 수정
  src/services/api.ts
Labels: fix

#173 [S-5] 탑 네비게이션 바에 배너, 알람배지를 추가하라
  src/components/common/TopNavBar.tsx
  src/services/api.ts
  src/styles/TopNavBarStyle.ts
Labels: feature

#174 [S-5] 홈 화면에 필요한 아이콘을 추가 및 삭제
  src/assets/calendar_icon.svg
  src/assets/lock_icon.svg
  src/assets/logo.svg
  src/assets/plus_icon.svg
  src/assets/search_icon.svg
  src/assets/time_icon.svg
Labels: chore

#177 [S-5] 달력에 스타일을 적용하라
  src/components/CalendarList.tsx
  src/components/common/Calendar.tsx
  src/styles/CalendarListStyle.ts
  src/styles/GlobalStyle.ts
  src/styles/MeetingListStyle.ts
Labels: feature

#178 [S-5] 홈 모임목록에 스타일을 적용하라
  src/components/ListContent.tsx
  src/components/MeetingList.tsx
  src/styles/AttendantsContentStyle.ts
  src/styles/ListContentStyle.ts
  src/utils/utils.ts
Labels: feature

#179 [S-5] 검색페이지에 예외처리를 하라
  src/components/common/SearchForm.tsx
  src/pages/SearchPage.tsx
  src/styles/SearchFormStyle.ts
Labels: feature

#180 [S-5] 사용하지 않는 꺽쇠제거
  src/components/common/ModalAccordion.tsx
  src/components/common/SortbyCategories.tsx
Labels: chore

#181 [S-5] 참여인원수/정원수 예외처리
  src/components/ListContent.tsx
Labels: chore

#182 [S-5] 프로필 페이지 공통 네비게이션 바 컴포넌트명 변경+
  src/components/InfoDeveloper.tsx
  src/components/InfoPrivacy.tsx
  src/pages/AlarmListPage.tsx
  src/pages/FollowPage.tsx
  src/styles/ProfileSubPageStyle.ts
Labels: chore

#183 [S-5] 디테일 페이지 모임 입장 후 상세페이지 부분적으로 바뀜, 리뷰 페이지 생성
  src/App.tsx
  src/assets/review_bad.svg
  src/assets/review_good.svg
  src/components/Comment.tsx
  src/components/common/DetailAttendList.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailMeetingInfo.tsx
  src/components/common/DetailNavBar.tsx
  src/pages/DetailPage.tsx
  src/pages/MettingReviewPage.tsx
  src/services/api.ts
  src/styles/MettingReviewPageStyle.ts
  src/types/DetailTypes.ts
Labels: feature

#184 [S-5] 프로필 서브페이지 작업
  src/App.tsx
  src/assets/404page.svg
  src/components/InfoDeveloper.tsx
  src/pages/AccountPage.tsx
  src/pages/FollowPage.tsx
  src/pages/InfoDeveloperPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SettingPage.tsx
  src/styles/ProfileSubPageStyle.ts
Labels: feature

#185 [S-5] 상세페이지 모임 입장 후 리뷰 작성 결과가 false만 나오는 부분 수정,
  src/components/common/DetailButton.tsx
  src/pages/DetailPage.tsx
  src/services/api.ts
Labels: feature

#186 [S-5] 모임 시작시간이 지난 후 상세페이지 입장시 안내문구 뜸
  src/components/Comment.tsx
  src/components/common/DetailButton.tsx
Labels: docs

#188 [S-5] 회원가입 페이지 스타일을 수정하였습니다.
  src/hooks/useAlert.ts
  src/pages/RePasswordPage.tsx
  src/pages/SignupPage.tsx
Labels: refactor, chore

#189 [S-5]로그인 페이지의 스타일을 추가하였습니다.
  src/pages/LoginPage.tsx
  src/styles/LoginFormStyle.ts
Labels: docs, refactor

#194 [S-5]댓글 컴포넌트에 사용되는 아이콘을 추가하였습니다.
  src/assets/n_comment_master.svg
  src/assets/n_send.svg
Labels: feature

#195 [S-5] 모임 입장 후 상세 페이지에서 댓글을 작성할 수 없도록 수정하였습니다
  src/components/Comment.tsx
  src/styles/CommentStyle.ts
Labels: feature, chore

#198 [S-5] 폼데이터관련 로직을 리팩터링하라
  src/services/api.ts
Labels: refactor

#199 [S-5] 토글의 기능을 수정하라
  src/components/Toggle.tsx
  src/components/common/ModalForm.tsx
Labels: feature

#200 [S-5] 나의 모임목록을 이번,다음달 것도 가져와라
  src/assets/meeting_img.svg
  src/components/CalendarList.tsx
  src/components/MeetingList.tsx
  src/components/common/Calendar.tsx
  src/components/common/ModalAccordion.tsx
  src/pages/HomePage.tsx
  src/styles/CalendarListStyle.ts
  src/styles/GlobalStyle.ts
  src/styles/MeetingListStyle.ts
  src/types/AppTypes.ts
  src/utils/utils.ts
Labels: feature

#201 [S-5] 작성/수정 페이지의 기능을 업데이트하라
  src/components/common/ModalAccordionButton.tsx
  src/hooks/useChangePostForm.ts
  src/hooks/useShowModalAccordion.ts
  src/pages/PostPage.tsx
  src/utils/utils.ts
Labels: feature

#202 [S-5] 검색페이지에서 검색결과가 없을때의 로직을 수정하라
  src/pages/SearchPage.tsx
Labels: refactor

#203 [S-5] 디테일 페이지 하단 버튼을 마스터와 멤버의 컴포넌트로 나눠서 작업하였습니다
  src/components/ButtonMeetingMaster.tsx
  src/components/ButtonMeetingMember.tsx
  src/components/Comment.tsx
  src/components/common/DetailAttendList.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailMeetingInfo.tsx
  src/components/common/DetailNavBar.tsx
  src/pages/AccountPage.tsx
  src/pages/DetailPage.tsx
  src/pages/ProfilePage.tsx
  src/styles/ProfileSubPageStyle.ts
  src/types/DetailTypes.ts
Labels: fix, refactor

#205 [S-5] 홈화면에 필요한 아이콘을 가져와라
  public/favicon.png
  public/index.html
  src/assets/banner_1.svg
  src/assets/banner_2.svg
  src/assets/banner_3.svg
  src/assets/category_alcohol.svg
  src/assets/category_all.svg
  src/assets/category_chat.svg
  src/assets/category_food.svg
  src/assets/category_games.svg
  src/assets/category_hobbies.svg
  src/assets/category_movies.svg
  src/assets/category_study.svg
  src/assets/lock_icon.svg
  src/assets/more_icon.svg
  src/assets/plus_icon.svg
  src/assets/search_icon.svg
  src/index.tsx
Labels: feature

#206 [S-5] 홈화면의 최종 스타일을 적용하라
  src/components/AttendantsContent.tsx
  src/components/CalendarList.tsx
  src/components/ListContent.tsx
  src/components/MeetingList.tsx
  src/components/common/Categories.tsx
  src/components/common/TopNavBar.tsx
  src/services/api.ts
  src/styles/AttendantsContentStyle.ts
  src/styles/CalendarListStyle.ts
  src/styles/CategoriesStyle.ts
  src/styles/GlobalStyle.ts
  src/styles/ListContentStyle.ts
  src/styles/LoadingStyle.ts
  src/styles/MeetingListStyle.ts
  src/styles/SortbyCategoriesStyle.ts
  src/styles/TopNavBarStyle.ts
Labels: feature

#207 [S-5] 검색화면의 최종 스타일을 적용하라
  src/assets/home_search_icon.svg
  src/assets/search_icon.svg
  src/components/common/SearchForm.tsx
  src/components/common/TopNavBar.tsx
  src/styles/GlobalStyle.ts
  src/styles/SearchFormStyle.ts
  src/styles/TopNavBarStyle.ts
Labels: feature

#210 [S-5] 프로필페이지에 스타일을 적용하라
  src/assets/Frame_user.svg
  src/assets/profile_camera_icon.svg
  src/assets/profile_pencil_icon.svg
  src/assets/right_arrow_icon.svg
  src/assets/user_img.svg
  src/components/AttendantsContent.tsx
  src/components/Comment.tsx
  src/components/ProfileModalForm.tsx
  src/components/Toggle.tsx
  src/components/common/DetailAttendList.tsx
  src/components/common/ModalAccordionButton.tsx
  src/pages/AccountPage.tsx
  src/pages/FollowPage.tsx
  src/pages/ProfilePage.tsx
  src/styles/DetailAttendListStyle.ts
  src/styles/ModalStyle.ts
  src/styles/ProfileStyle.ts
Labels: feature

#211 [S-5] 작성/수정 페이지에 최종 스타일을 적용하라
  src/styles/ButtonStyle.ts
  src/styles/CommentStyle.ts
  src/styles/FormStyle.ts
  src/styles/GlobalStyle.ts
  src/styles/SearchFormStyle.ts
  src/styles/ToggleStyle.ts
Labels: feature

#212 [S-5] 탑네브바에 최종 스타일을 적용하라
  src/components/common/TopNavBar.tsx
  src/styles/TopNavBarStyle.ts
Labels: feature

#213 [S-5] 작성/수정페이지의 입력안되는 입력창을 수정하라
  src/hooks/useChangePostForm.ts
  src/pages/PostPage.tsx
Labels: feature

#214 [S-5] 홈화면에서 카테고리 무한스크롤 요청수정
  src/components/CalendarList.tsx
  src/components/ListContent.tsx
  src/components/MeetingList.tsx
  src/hooks/useInfiniteScroll.ts
  src/services/api.ts
Labels: refactor, feature

#215 [S-5] 배포에러를 해결하라
  src/components/common/TopNavBar.tsx
Labels: fix

#221 [S-5] 홈화면에서 사용될 배너이미지 수정
  src/assets/banner_1.svg
  src/assets/banner_2.svg
  src/assets/banner_3.svg
Labels: chore
