Repository MoyeoProject/moyeo-FE, pull requests merged in 2023-01, with the labels that each got.

#8 [S-1] 사용자는 홈화면에서 모임목록을 볼 수 있다
  src/components/common/ListItems.tsx
  src/pages/HomePage.tsx
  src/types/AppTypes.ts
Labels: feature

#18 [S-1] 사용자는 참석/취소버튼, 수정버튼(방장만)을 사용할 수 있다
  package-lock.json
  package.json
  src/components/Calendar.tsx
  src/components/common/ListCategories.tsx
  src/components/common/ListItems.tsx
  src/components/common/ModalContent.tsx
  src/components/common/PostButton.tsx
  src/index.tsx
  src/pages/HomePage.tsx
  src/services/api.ts
  src/styles/GlobalStyle.ts
  src/styles/ModalContentStyle.ts
Labels: feature

#17 [S-1] 사용자는 나의모임탭을 누르면 달력을 볼 수 있다
  src/components/Calendar.tsx
  src/components/common/ListCategories.tsx
  src/components/common/ListItems.tsx
  src/pages/HomePage.tsx
Labels: feature

#22 [S-1] 사용자는 로그인 버튼클릭 혹은 엔터로 로그인 할 수 있다
  src/components/KakaoLoginButton.tsx
  src/components/LoginButton.tsx
  src/components/LoginForm.tsx
  src/components/SignupForm.tsx
  src/pages/AuthPage.tsx
  src/services/api.ts
  src/types/AppTypes.ts
Labels: feature

#9 [S-1] 모임목록에 무한스크롤 기능을 적용하라
  src/components/SearchForm.tsx
  src/components/common/ListItems.tsx
  src/hooks/useInfiniteScroll.ts
  src/hooks/useInfiniteScrollByPageId.ts
  src/pages/HomePage.tsx
  src/slice.ts
  src/types/AppTypes.ts
Labels: feature

#31 [S-2] 신규/인기/검색에 따른 모임목록을 서버데이터 as-is로 구현
  src/components/SearchForm.tsx
  src/components/common/ListCategories.tsx
  src/hooks/useSetMeetingList.ts
  src/pages/HomePage.tsx
  src/services/api.ts
Labels: feature

#30 [S-2] 모임목록 무한스크롤 기능을 서버데이터 as-is로 구현
  src/components/MeetingList.tsx
  src/hooks/useInfiniteScroll.ts
  src/hooks/useInfiniteScrollByPageId.ts
  src/hooks/useIntersect.ts
  src/services/api.ts
Labels: feature

#32 [S-2] 홈화면 모임목록 렌더링 에러를 해결하라
  src/components/SearchForm.tsx
  src/components/common/ListCategories.tsx
  src/hooks/useInfiniteScroll.ts
  src/hooks/useSetMeetingList.ts
  src/modules/homeSlice.ts
  src/pages/HomePage.tsx
  src/store.ts
Labels: fix

#36 [S-2] 모임목록에 참석자 프로필 이미지 표시
  public/img/exuser.jpg
  src/components/ListContent.tsx
  src/styles/GlobalStyle.ts
  src/types/AppTypes.ts
Labels: chore

#38 [S-2] 모임 참석/취소 기능을 서버데이터 as-is로 구현
  src/components/ButtonContent.tsx
  src/components/SearchForm.tsx
  src/components/common/ModalContent.tsx
  src/components/common/ModalForm.tsx
  src/components/common/PostButton.tsx
  src/hooks/useChangeInputField.ts
  src/hooks/useChangeSearchField.ts
  src/services/api.ts
  src/styles/ModalFormStyle.ts
Labels: feature

#47 [S-2] 사용자는 로그아웃 할 수 있다
  src/components/KakaoLoginButton.tsx
  src/components/PostContentForm.tsx
  src/components/SearchForm.tsx
  src/components/common/ModalAccordion.tsx
  src/components/common/ModalForm.tsx
  src/components/common/TopNavBar.tsx
  src/hooks/useChangeInputField.ts
  src/hooks/useChangePostForm.ts
  src/pages/PostPage.tsx
  src/services/api.ts
  src/types/AppTypes.ts
Labels: feature

#45 [S-2] 사용자는 '모임에 대해 설명해주세요' 폼을 입력할 수 있다
  src/components/PostContentForm.tsx
  src/components/common/ModalAccordion.tsx
  src/hooks/useChangePostForm.ts
  src/pages/PostPage.tsx
  src/types/AppTypes.ts
Labels: feature

#51 Detail memberlist
  src/components/KakaoLoginButton.tsx
  src/components/common/DetailAttendList.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailMeetingInfo.tsx
  src/services/api.ts
Labels: feature

#54 Detail memberlist
  src/components/Comment.tsx
  src/components/KakaoLoginButton.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailNavBar.tsx
  src/services/api.ts
Labels: feature

#55 Detail memberlist
  src/components/Comment.tsx
  src/components/KakaoLoginButton.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailMeetingInfo.tsx
  src/pages/DetailPage.tsx
Labels: feature

#56 [S-2] 작성/수정페이지 모달아코디언버튼을 만들어라
  src/components/PostContentForm.tsx
  src/components/common/ModalAccordion.tsx
  src/components/common/ModalAccordionButton.tsx
  src/hooks/useChangePostForm.ts
  src/hooks/useShowModalAccordion.ts
  src/pages/PostPage.tsx
Labels: refactor, feature

#58 [S-2] 리액트 데이터피커 라이브러리 설치
  package-lock.json
  package.json
Labels: setting

#59 [S-2] 작성/수정페이지 모달아코디언버튼을 캘린터로 만들어라
  src/components/common/ModalAccordion.tsx
  src/components/common/ModalAccordionButton.tsx
  src/hooks/useShowModalAccordion.ts
  src/utils/utils.ts
Labels: feature

#62 [S-2] 작성/수정페이지에 시간 선택창을 만들고 캘린더 로직 수정
  package-lock.json
  package.json
  src/components/common/ModalAccordion.tsx
  src/components/common/ModalAccordionButton.tsx
  src/hooks/useChangePostForm.ts
  src/hooks/useShowModalAccordion.ts
  src/pages/PostPage.tsx
  src/types/AppTypes.ts
  src/utils/utils.ts
Labels: feature

#65 [S-2] 작성/수정페이지에 공개설정 토글버튼을 만들어라
  src/components/Toggle.tsx
  src/components/common/ModalForm.tsx
  src/components/common/PostButton.tsx
  src/hooks/useChangePostForm.ts
  src/pages/PostPage.tsx
  src/styles/ToggleStyle.ts
  src/types/AppTypes.ts
Labels: feature

#66 [S-2] 작성/수정페이지 항목에 대한 예외처리
  src/components/common/ModalAccordion.tsx
  src/components/common/ModalAccordionButton.tsx
  src/hooks/useShowModalAccordion.ts
Labels: feature

#68 Detail member list
  src/components/KakaoLoginButton.tsx
  src/components/KakaoShareButton.tsx
  src/components/common/DetailMeetingInfo.tsx
  src/components/common/DetailNavBar.tsx
  src/pages/DetailPage.tsx
  src/react-app-env.d.ts
  src/styles/GlobalStyle.ts
  src/types/DetailTypes.ts
Labels: refactor, feature

#71 [S-2] 모임글 작성/수정완료 서버데이터 as-is로 구현
  src/components/ButtonContent.tsx
  src/components/common/ModalAccordionButton.tsx
  src/components/common/TopNavBar.tsx
  src/pages/PostPage.tsx
  src/services/api.ts
Labels: feature

#74 [S-3] 홈 탑 네비게이션 바에 와이어프레임을 적용하라
  src/assets/logo.svg
  src/assets/plus_icon.svg
  src/assets/profile_icon.svg
  src/assets/search_icon.svg
  src/components/common/ListCategories.tsx
  src/components/common/TopNavBar.tsx
  src/pages/HomePage.tsx
  src/styles/ListCategoriesStyle.ts
  src/styles/TopNavBarStyle.ts
Labels: feature

#79 [S-3] 홈 탑 네비게이션 바에 와이어프레임을 적용하라 - 2
  src/assets/category_img.svg
  src/components/common/Categories.tsx
  src/components/common/SearchForm.tsx
  src/components/common/SortbyCategories.tsx
  src/components/common/TopNavBar.tsx
  src/pages/HomePage.tsx
  src/styles/CategoriesStyle.ts
  src/styles/GlobalStyle.ts
  src/styles/SearchFormStyle.ts
  src/styles/SortbyCategoriesStyle.ts
Labels: feature

#82 [S-3] 모임목록에 필요한 아이콘 추가
  src/assets/calendar_icon.svg
  src/assets/lock_icon.svg
  src/assets/profile_img.svg
  src/assets/time_icon.svg
Labels: chore

#83 [S-3] 모임목록에 와이어프레임을 적용하라
  src/components/AttendantsContent.tsx
  src/components/ButtonContent.tsx
  src/components/ListContent.tsx
  src/components/MeetingList.tsx
  src/components/common/PostButton.tsx
  src/styles/AttendantsContentStyle.ts
  src/styles/GlobalStyle.ts
  src/styles/ListContentStyle.ts
  src/styles/MeetingListStyle.ts
  src/styles/PostButtonStyle.ts
  src/types/AppTypes.ts
  src/utils/utils.ts
Labels: feature

#85 [S-3] 상세페이지 댓글 탭 와이어프레임 적용하기
  src/assets/bad_icon.svg
  src/assets/calendar_detail.svg
  src/assets/chevron-left.svg
  src/assets/clock_icon.svg
  src/assets/detail_bell-ringing.svg
  src/assets/detail_logout.svg
  src/assets/detail_share.svg
  src/assets/good_icon.svg
  src/components/Comment.tsx
  src/components/common/DetailAttendList.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailCategories.tsx
  src/components/common/DetailMeetingInfo.tsx
  src/components/common/DetailNavBar.tsx
  src/components/common/FollowButton.tsx
  src/pages/AuthPage.tsx
  src/styles/DetailAttendListStyle.ts
  src/styles/DetailButtonStyle.ts
  src/styles/DetailMeetingInfoStyle.ts
  src/styles/DetailNavBarStyle.ts
  src/styles/DetailPageStyle.ts
  src/styles/GlobalStyle.ts
Labels: feature

#86 [S-3]로그인 페이지 와이어 프레임 디자인 적용
  src/assets/Loginlogo.svg
  src/components/LoginForm.tsx
  src/styles/LoginFormStyle.ts
Labels: docs

#87 [S-3] Encountered two children with the same key 에러 해결
  src/components/common/Categories.tsx
  src/hooks/useInfiniteScroll.ts
Labels: fix

#89 [S-3] 모임목록의 참석/취소버튼 기능을 수정하라
  src/components/ButtonContent.tsx
  src/components/Toggle.tsx
  src/components/common/ModalForm.tsx
  src/components/common/PostButton.tsx
  src/services/api.ts
Labels: feature

#90 [S-3] 모달폼을 개선하라
  src/components/Toggle.tsx
  src/components/common/ModalForm.tsx
  src/components/common/PostButton.tsx
Labels: refactor, feature

#91 [S-3] 모달폼에 와이어프레임 스타일을 적용하라
  src/components/ButtonContent.tsx
  src/components/common/ModalAccordion.tsx
  src/styles/ButtonStyle.ts
  src/styles/ModalFormStyle.ts
  src/styles/PostButtonStyle.ts
Labels: feature

#94 [S-3] 상세페이지 모임 링크 생성 버튼 모달 구현
  src/assets/Frame_plus.svg
  src/components/DetailMeetLinkButton.tsx
  src/components/common/DetailAttendList.tsx
  src/components/common/DetailButton.tsx
  src/pages/DetailPage.tsx
  src/services/api.ts
  src/styles/CommentStyle.ts
  src/styles/DetailAttendListStyle.ts
  src/styles/DetailButtonStyle.ts
  src/styles/DetailPageStyle.ts
  src/types/DetailTypes.ts
Labels: feature

#97 [S-3] 모임 작성/수정폼에 와이어프레임을 적용하라
  src/assets/bottom_arrow_icon.svg
  src/assets/left_arrow_icon.svg
  src/assets/logo.svg
  src/components/DetailMeetLinkButton.tsx
  src/components/common/ModalAccordion.tsx
  src/components/common/ModalAccordionButton.tsx
  src/components/common/ModalForm.tsx
  src/components/common/TopNavBar.tsx
  src/pages/PostPage.tsx
  src/styles/FormStyle.ts
  src/styles/ModalStyle.ts
  src/styles/TopNavBarStyle.ts
Labels: feature

#99 [S-3] 모임 작성/수정폼에 와이어프레임을 적용하라 (2)
  src/assets/right_arrow_icon.svg
  src/components/Toggle.tsx
  src/pages/PostPage.tsx
  src/styles/ButtonStyle.ts
  src/styles/ToggleStyle.ts
Labels: feature

#100 [S-3] 디테일 페이지 작은 수정모음, 카카오 로그인 리다이렉트 env변경
  src/components/Comment.tsx
  src/components/common/DetailCategories.tsx
  src/components/common/DetailNavBar.tsx
  src/components/common/FollowButton.tsx
  src/pages/DetailPage.tsx
Labels: feature

#102 [S-3] 중간 점검 후, 수정사항 반영
  src/assets/Frame_user.svg
  src/components/Comment.tsx
  src/components/DetailMeetLinkButton.tsx
  src/components/common/DetailAttendList.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailCategories.tsx
  src/components/common/DetailMeetingInfo.tsx
  src/components/common/DetailNavBar.tsx
  src/pages/DetailPage.tsx
  src/services/api.ts
  src/styles/CommentStyle.ts
  src/styles/DetailButtonStyle.ts
  src/types/DetailTypes.ts
Labels: feature

#105 [S-3] 디테일페이지 수정사항 적용
  package-lock.json
  package.json
  src/components/Comment.tsx
  src/components/DetailMeetLinkButton.tsx
  src/components/LoginForm.tsx
  src/components/SignupForm.tsx
  src/components/common/DetailAttendList.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailCategories.tsx
  src/components/common/DetailNavBar.tsx
  src/services/api.ts
  src/styles/CommentStyle.ts
  src/styles/DetailAttendListStyle.ts
  src/styles/DetailPageStyle.ts
Labels: feature

#104 [S-3] 앱 이름변경 및 iOS 사파리 기본 스타일 제거
  public/index.html
  src/index.tsx
Labels: chore

#106 [S-3] 모달아코디언에 와이어프레임을 적용하라
  src/assets/modal_plus_icon.svg
  src/components/common/ModalAccordion.tsx
  src/styles/ModalStyle.ts
Labels: feature

#107 [S-3] 모임 작성페이지 사용자 코멘트 반영
  package-lock.json
  src/components/common/ModalAccordion.tsx
  src/components/common/ModalAccordionButton.tsx
  src/components/common/ModalForm.tsx
  src/hooks/useShowModalAccordion.ts
  src/styles/FormStyle.ts
  src/styles/GlobalStyle.ts
  src/types/AppTypes.ts
Labels: feature

#108 [S-3] 탑네브바랑 스크롤되는 부분 끊기는 것 개선
  src/styles/FormStyle.ts
  src/styles/MeetingListStyle.ts
Labels: chore

#109 [S-3] 컨텐츠 문구관련 수정
  src/components/common/PostButton.tsx
  src/components/common/SearchForm.tsx
  src/hooks/useShowModalAccordion.ts
Labels: chore

#110 [S-3] 모달 달력에 기본 레이아웃을 적용하라
  src/components/common/ModalAccordion.tsx
  src/components/common/ModalAccordionButton.tsx
  src/styles/GlobalStyle.ts
  src/styles/ModalStyle.ts
Labels: feature

#112 [S-3] 로딩 및 에러를 표시하라
  package-lock.json
  package.json
  src/assets/error.json
  src/assets/loading.json
  src/index.tsx
  tsconfig.json
Labels: feature

#113 [S-3] 쿼리무효화로 데이터를 화면에 바로 업데이트하라
  src/components/MeetingList.tsx
  src/components/common/SortbyCategories.tsx
  src/hooks/useInfiniteScroll.ts
  src/modules/homeSlice.ts
  src/pages/HomePage.tsx
  src/store.ts
Labels: refactor, feature

#114 [S-3] 모달창 바깥을 클릭하면 모달창이 닫힌다
  src/components/Toggle.tsx
  src/components/common/ModalAccordion.tsx
  src/components/common/ModalForm.tsx
  src/components/common/PostButton.tsx
  src/hooks/useCloseModal.ts
  src/styles/ModalStyle.ts
Labels: refactor, feature

#116 [S-4] 모달 캘린더 스타일 적용
  src/assets/cal_left_arrow_icon.svg
  src/assets/cal_right_arrow_icon.svg
  src/components/common/ModalAccordion.tsx
  src/components/common/TopNavBar.tsx
  src/styles/GlobalStyle.ts
Labels: feature

#121 [S-4] 모임목록에 참석/취소/수정 버튼 제거
  src/components/ButtonContent.tsx
  src/components/ListContent.tsx
  src/components/MeetingList.tsx
  src/components/common/PostButton.tsx
  src/styles/AttendantsContentStyle.ts
  src/styles/ListContentStyle.ts
Labels: feature

#123 [S-4] 카테고리로 모임목록을 불러와라
  src/components/common/Categories.tsx
  src/components/common/SearchForm.tsx
  src/components/common/SortbyCategories.tsx
  src/hooks/useInfiniteScroll.ts
  src/index.tsx
  src/services/api.ts
  src/styles/CategoriesStyle.ts
  src/styles/MeetingListStyle.ts
  src/styles/SortbyCategoriesStyle.ts
Labels: refactor, feature

#125 [S-4] 모달아코디언에서 캘린더 컴포넌트를 분리
  src/components/common/Calendar.tsx
  src/components/common/ModalAccordion.tsx
  src/styles/GlobalStyle.ts
  src/styles/ModalStyle.ts
Labels: refactor

#126 [S-4] 캘린더 모임목록을 구현
  src/components/Calendar.tsx
  src/components/CalendarList.tsx
  src/components/MeetingList.tsx
  src/components/common/TopNavBar.tsx
  src/pages/HomePage.tsx
  src/services/api.ts
  src/styles/AttendantsContentStyle.ts
  src/styles/CalendarListStyle.ts
  src/styles/ListContentStyle.ts
  src/styles/MeetingListStyle.ts
Labels: feature

#127 [S-4] 모임 달력에 뱃지를 추가하라
  src/components/CalendarList.tsx
  src/components/common/Calendar.tsx
  src/components/common/ModalAccordion.tsx
  src/styles/GlobalStyle.ts
Labels: feature

#131 [S-4] 임박한 모임까지 남은 시간을 카운트다운으로 표시하라
  src/components/CalendarList.tsx
  src/utils/utils.ts
Labels: feature

#133 [S-4] 달력날짜에 해당하는 모임목록을 보여줘라
  package-lock.json
  src/components/CalendarList.tsx
  src/components/MeetingList.tsx
  src/components/common/Calendar.tsx
  src/styles/CalendarListStyle.ts
  src/styles/MeetingListStyle.ts
Labels: feature

#134 [S-4] 사용하지 않는 라이브러리 제거
  package-lock.json
  package.json
Labels: setting

#136 [S-4] 프로필페이지를 서버데이터 as-is로 구현
  src/App.tsx
  src/assets/black_right_arrow_Icon.svg
  src/assets/profile_img.svg
  src/components/ListContent.tsx
  src/components/common/TopNavBar.tsx
  src/pages/ProfilePage.tsx
  src/services/api.ts
  src/styles/TopNavBarStyle.ts
Labels: feature

#139 [S-4] 홈페이지의 에러를 고쳐라
  src/components/CalendarList.tsx
  src/components/MeetingList.tsx
  src/components/common/SearchForm.tsx
  src/components/common/SortbyCategories.tsx
  src/hooks/useInfiniteScroll.ts
  src/pages/HomePage.tsx
  src/services/api.ts
Labels: fix, refactor, feature

#141 [S-4] 유저의 팔로우/팔로워 페이지 구현
  src/App.tsx
  src/components/AlarmList.tsx
  src/components/InfoDeveloper.tsx
  src/components/InfoPrivacy.tsx
  src/components/common/DetailAttendList.tsx
  src/components/common/FollowButton.tsx
  src/pages/FollowPage.tsx
  src/pages/InfoEX.tsx
  src/services/api.ts
  src/styles/CommentStyle.ts
  src/styles/DetailAttendListStyle.ts
  src/styles/InfoBoxStyle.ts
Labels: feature

#142 [S-4] 알림 리스트를 생성하여 댓글작성,모임참여 등 리스트를 볼 수 있습니다., 알림연결은 수정중.
  src/components/AlarmList.tsx
  src/pages/InfoEX.tsx
  src/services/api.ts
Labels: bug, feature

#143 [S-4]로그인, 회원가입 페이지 height style수정하였습니다
  src/pages/SignupPage.tsx
  src/styles/InfoBoxStyle.ts
  src/styles/LoginFormStyle.ts
Labels: refactor

#144 [S-4] detail-page height수정 및 페이지 확대시 버튼 사라지는 버그 해결
  src/styles/CommentStyle.ts
  src/styles/DetailPageStyle.ts
Labels: refactor

#146 [S-4] 디테일 댓글 페이지에서 사용자 프로필 사진이 없을 경우, 기본 이미지로 채워넣었다.
  src/components/Comment.tsx
Labels: chore

#148 [S-4] 에러 코드 수정
  src/components/DetailButtonModal.tsx
Labels: chore

#150 [S-4] 알림 구독 연결 확인, eventSource사용 - 실시간 알림은 확인중
  src/components/AlarmList.tsx
  src/components/InfoPrivacy.tsx
  src/pages/InfoEX.tsx
  src/services/api.ts
  src/types/DetailTypes.ts
Labels: feature

#145 [S-4] 프로필 모달폼으로 사용자정보를 수정하라
  src/components/ProfileModalForm.tsx
  src/hooks/useChangePostForm.ts
  src/pages/ProfilePage.tsx
  src/services/api.ts
  src/types/AppTypes.ts
Labels: feature

#152 [S-5] 상세페이지 디자인 변경 및 레이아웃 수정
  src/components/common/DetailCategories.tsx
  src/components/common/DetailMeetingInfo.tsx
  src/components/common/DetailNavBar.tsx
  src/components/common/FollowButton.tsx
  src/components/common/TopNavBar.tsx
  src/styles/DetailAttendListStyle.ts
  src/styles/DetailButtonStyle.ts
  src/styles/DetailMeetingInfoStyle.ts
  src/styles/DetailNavBarStyle.ts
Labels: feature, chore

#153 [S-5] 토스트알럿 라이브러리 도입 및 적용
  package-lock.json
  package.json
  src/components/Comment.tsx
  src/components/DetailButtonModal.tsx
  src/components/KakaoLoginButton.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailNavBar.tsx
  src/components/common/ModalForm.tsx
  src/components/common/SearchForm.tsx
  src/hooks/useAttendButton.ts
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/services/api.ts
  src/styles/ModalStyle.ts
  src/styles/TopNavBarStyle.ts
Labels: setting, chore

#154 [S-5] 상세 페이지 디자인 수정 및 기능 보완
  src/components/Comment.tsx
  src/components/DetailButtonModal.tsx
  src/components/common/DetailButton.tsx
  src/components/common/DetailCategories.tsx
  src/components/common/DetailNavBar.tsx
  src/pages/DetailPage.tsx
  src/styles/CommentStyle.ts
Labels: feature, chore

#157 [S-5] 달력관련 ui를 수정하라
  src/components/CalendarList.tsx
  src/components/common/Calendar.tsx
  src/pages/HomePage.tsx
Labels: fix, chore
